/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetStatusGet200ResponseDataMagnetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetStatusGet200ResponseDataMagnetsInner{}

// MagnetStatusGet200ResponseDataMagnetsInner struct for MagnetStatusGet200ResponseDataMagnetsInner
type MagnetStatusGet200ResponseDataMagnetsInner struct {
	Id *int64 `json:"id,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusCode *int64 `json:"statusCode,omitempty"`
	Downloaded *int64 `json:"downloaded,omitempty"`
	Uploaded *int64 `json:"uploaded,omitempty"`
	Seeders *int64 `json:"seeders,omitempty"`
	DownloadSpeed *int64 `json:"downloadSpeed,omitempty"`
	UploadSpeed *int64 `json:"uploadSpeed,omitempty"`
	UploadDate *int64 `json:"uploadDate,omitempty"`
	CompletionDate *int64 `json:"completionDate,omitempty"`
	Links []MagnetStatusGet200ResponseDataMagnetsInnerLinksInner `json:"links,omitempty"`
}

// NewMagnetStatusGet200ResponseDataMagnetsInner instantiates a new MagnetStatusGet200ResponseDataMagnetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetStatusGet200ResponseDataMagnetsInner() *MagnetStatusGet200ResponseDataMagnetsInner {
	this := MagnetStatusGet200ResponseDataMagnetsInner{}
	return &this
}

// NewMagnetStatusGet200ResponseDataMagnetsInnerWithDefaults instantiates a new MagnetStatusGet200ResponseDataMagnetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetStatusGet200ResponseDataMagnetsInnerWithDefaults() *MagnetStatusGet200ResponseDataMagnetsInner {
	this := MagnetStatusGet200ResponseDataMagnetsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetId(v int64) {
	o.Id = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetFilename(v string) {
	o.Filename = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetSize(v int64) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetStatus(v string) {
	o.Status = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetStatusCode() int64 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int64
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetStatusCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int64 and assigns it to the StatusCode field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetStatusCode(v int64) {
	o.StatusCode = &v
}

// GetDownloaded returns the Downloaded field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetDownloaded() int64 {
	if o == nil || IsNil(o.Downloaded) {
		var ret int64
		return ret
	}
	return *o.Downloaded
}

// GetDownloadedOk returns a tuple with the Downloaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetDownloadedOk() (*int64, bool) {
	if o == nil || IsNil(o.Downloaded) {
		return nil, false
	}
	return o.Downloaded, true
}

// HasDownloaded returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasDownloaded() bool {
	if o != nil && !IsNil(o.Downloaded) {
		return true
	}

	return false
}

// SetDownloaded gets a reference to the given int64 and assigns it to the Downloaded field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetDownloaded(v int64) {
	o.Downloaded = &v
}

// GetUploaded returns the Uploaded field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploaded() int64 {
	if o == nil || IsNil(o.Uploaded) {
		var ret int64
		return ret
	}
	return *o.Uploaded
}

// GetUploadedOk returns a tuple with the Uploaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploadedOk() (*int64, bool) {
	if o == nil || IsNil(o.Uploaded) {
		return nil, false
	}
	return o.Uploaded, true
}

// HasUploaded returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasUploaded() bool {
	if o != nil && !IsNil(o.Uploaded) {
		return true
	}

	return false
}

// SetUploaded gets a reference to the given int64 and assigns it to the Uploaded field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetUploaded(v int64) {
	o.Uploaded = &v
}

// GetSeeders returns the Seeders field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetSeeders() int64 {
	if o == nil || IsNil(o.Seeders) {
		var ret int64
		return ret
	}
	return *o.Seeders
}

// GetSeedersOk returns a tuple with the Seeders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetSeedersOk() (*int64, bool) {
	if o == nil || IsNil(o.Seeders) {
		return nil, false
	}
	return o.Seeders, true
}

// HasSeeders returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasSeeders() bool {
	if o != nil && !IsNil(o.Seeders) {
		return true
	}

	return false
}

// SetSeeders gets a reference to the given int64 and assigns it to the Seeders field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetSeeders(v int64) {
	o.Seeders = &v
}

// GetDownloadSpeed returns the DownloadSpeed field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetDownloadSpeed() int64 {
	if o == nil || IsNil(o.DownloadSpeed) {
		var ret int64
		return ret
	}
	return *o.DownloadSpeed
}

// GetDownloadSpeedOk returns a tuple with the DownloadSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetDownloadSpeedOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadSpeed) {
		return nil, false
	}
	return o.DownloadSpeed, true
}

// HasDownloadSpeed returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasDownloadSpeed() bool {
	if o != nil && !IsNil(o.DownloadSpeed) {
		return true
	}

	return false
}

// SetDownloadSpeed gets a reference to the given int64 and assigns it to the DownloadSpeed field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetDownloadSpeed(v int64) {
	o.DownloadSpeed = &v
}

// GetUploadSpeed returns the UploadSpeed field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploadSpeed() int64 {
	if o == nil || IsNil(o.UploadSpeed) {
		var ret int64
		return ret
	}
	return *o.UploadSpeed
}

// GetUploadSpeedOk returns a tuple with the UploadSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploadSpeedOk() (*int64, bool) {
	if o == nil || IsNil(o.UploadSpeed) {
		return nil, false
	}
	return o.UploadSpeed, true
}

// HasUploadSpeed returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasUploadSpeed() bool {
	if o != nil && !IsNil(o.UploadSpeed) {
		return true
	}

	return false
}

// SetUploadSpeed gets a reference to the given int64 and assigns it to the UploadSpeed field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetUploadSpeed(v int64) {
	o.UploadSpeed = &v
}

// GetUploadDate returns the UploadDate field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploadDate() int64 {
	if o == nil || IsNil(o.UploadDate) {
		var ret int64
		return ret
	}
	return *o.UploadDate
}

// GetUploadDateOk returns a tuple with the UploadDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetUploadDateOk() (*int64, bool) {
	if o == nil || IsNil(o.UploadDate) {
		return nil, false
	}
	return o.UploadDate, true
}

// HasUploadDate returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasUploadDate() bool {
	if o != nil && !IsNil(o.UploadDate) {
		return true
	}

	return false
}

// SetUploadDate gets a reference to the given int64 and assigns it to the UploadDate field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetUploadDate(v int64) {
	o.UploadDate = &v
}

// GetCompletionDate returns the CompletionDate field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetCompletionDate() int64 {
	if o == nil || IsNil(o.CompletionDate) {
		var ret int64
		return ret
	}
	return *o.CompletionDate
}

// GetCompletionDateOk returns a tuple with the CompletionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetCompletionDateOk() (*int64, bool) {
	if o == nil || IsNil(o.CompletionDate) {
		return nil, false
	}
	return o.CompletionDate, true
}

// HasCompletionDate returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasCompletionDate() bool {
	if o != nil && !IsNil(o.CompletionDate) {
		return true
	}

	return false
}

// SetCompletionDate gets a reference to the given int64 and assigns it to the CompletionDate field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetCompletionDate(v int64) {
	o.CompletionDate = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetLinks() []MagnetStatusGet200ResponseDataMagnetsInnerLinksInner {
	if o == nil || IsNil(o.Links) {
		var ret []MagnetStatusGet200ResponseDataMagnetsInnerLinksInner
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) GetLinksOk() ([]MagnetStatusGet200ResponseDataMagnetsInnerLinksInner, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []MagnetStatusGet200ResponseDataMagnetsInnerLinksInner and assigns it to the Links field.
func (o *MagnetStatusGet200ResponseDataMagnetsInner) SetLinks(v []MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) {
	o.Links = v
}

func (o MagnetStatusGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetStatusGet200ResponseDataMagnetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	if !IsNil(o.Downloaded) {
		toSerialize["downloaded"] = o.Downloaded
	}
	if !IsNil(o.Uploaded) {
		toSerialize["uploaded"] = o.Uploaded
	}
	if !IsNil(o.Seeders) {
		toSerialize["seeders"] = o.Seeders
	}
	if !IsNil(o.DownloadSpeed) {
		toSerialize["downloadSpeed"] = o.DownloadSpeed
	}
	if !IsNil(o.UploadSpeed) {
		toSerialize["uploadSpeed"] = o.UploadSpeed
	}
	if !IsNil(o.UploadDate) {
		toSerialize["uploadDate"] = o.UploadDate
	}
	if !IsNil(o.CompletionDate) {
		toSerialize["completionDate"] = o.CompletionDate
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableMagnetStatusGet200ResponseDataMagnetsInner struct {
	value *MagnetStatusGet200ResponseDataMagnetsInner
	isSet bool
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInner) Get() *MagnetStatusGet200ResponseDataMagnetsInner {
	return v.value
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInner) Set(val *MagnetStatusGet200ResponseDataMagnetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetStatusGet200ResponseDataMagnetsInner(val *MagnetStatusGet200ResponseDataMagnetsInner) *NullableMagnetStatusGet200ResponseDataMagnetsInner {
	return &NullableMagnetStatusGet200ResponseDataMagnetsInner{value: val, isSet: true}
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


