/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the HostsPriorityGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostsPriorityGet200ResponseData{}

// HostsPriorityGet200ResponseData struct for HostsPriorityGet200ResponseData
type HostsPriorityGet200ResponseData struct {
	Hosts *map[string]int64 `json:"hosts,omitempty"`
}

// NewHostsPriorityGet200ResponseData instantiates a new HostsPriorityGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostsPriorityGet200ResponseData() *HostsPriorityGet200ResponseData {
	this := HostsPriorityGet200ResponseData{}
	return &this
}

// NewHostsPriorityGet200ResponseDataWithDefaults instantiates a new HostsPriorityGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostsPriorityGet200ResponseDataWithDefaults() *HostsPriorityGet200ResponseData {
	this := HostsPriorityGet200ResponseData{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *HostsPriorityGet200ResponseData) GetHosts() map[string]int64 {
	if o == nil || IsNil(o.Hosts) {
		var ret map[string]int64
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsPriorityGet200ResponseData) GetHostsOk() (*map[string]int64, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *HostsPriorityGet200ResponseData) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given map[string]int64 and assigns it to the Hosts field.
func (o *HostsPriorityGet200ResponseData) SetHosts(v map[string]int64) {
	o.Hosts = &v
}

func (o HostsPriorityGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostsPriorityGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	return toSerialize, nil
}

type NullableHostsPriorityGet200ResponseData struct {
	value *HostsPriorityGet200ResponseData
	isSet bool
}

func (v NullableHostsPriorityGet200ResponseData) Get() *HostsPriorityGet200ResponseData {
	return v.value
}

func (v *NullableHostsPriorityGet200ResponseData) Set(val *HostsPriorityGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableHostsPriorityGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableHostsPriorityGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostsPriorityGet200ResponseData(val *HostsPriorityGet200ResponseData) *NullableHostsPriorityGet200ResponseData {
	return &NullableHostsPriorityGet200ResponseData{value: val, isSet: true}
}

func (v NullableHostsPriorityGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostsPriorityGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


