/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetInstantGet200ResponseDataMagnetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetInstantGet200ResponseDataMagnetsInner{}

// MagnetInstantGet200ResponseDataMagnetsInner struct for MagnetInstantGet200ResponseDataMagnetsInner
type MagnetInstantGet200ResponseDataMagnetsInner struct {
	Magnet *string `json:"magnet,omitempty"`
	Hash *string `json:"hash,omitempty"`
	Instant *bool `json:"instant,omitempty"`
	Error *MagnetUploadGet200ResponseDataMagnetsInnerError `json:"error,omitempty"`
}

// NewMagnetInstantGet200ResponseDataMagnetsInner instantiates a new MagnetInstantGet200ResponseDataMagnetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetInstantGet200ResponseDataMagnetsInner() *MagnetInstantGet200ResponseDataMagnetsInner {
	this := MagnetInstantGet200ResponseDataMagnetsInner{}
	return &this
}

// NewMagnetInstantGet200ResponseDataMagnetsInnerWithDefaults instantiates a new MagnetInstantGet200ResponseDataMagnetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetInstantGet200ResponseDataMagnetsInnerWithDefaults() *MagnetInstantGet200ResponseDataMagnetsInner {
	this := MagnetInstantGet200ResponseDataMagnetsInner{}
	return &this
}

// GetMagnet returns the Magnet field value if set, zero value otherwise.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetMagnet() string {
	if o == nil || IsNil(o.Magnet) {
		var ret string
		return ret
	}
	return *o.Magnet
}

// GetMagnetOk returns a tuple with the Magnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetMagnetOk() (*string, bool) {
	if o == nil || IsNil(o.Magnet) {
		return nil, false
	}
	return o.Magnet, true
}

// HasMagnet returns a boolean if a field has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) HasMagnet() bool {
	if o != nil && !IsNil(o.Magnet) {
		return true
	}

	return false
}

// SetMagnet gets a reference to the given string and assigns it to the Magnet field.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) SetMagnet(v string) {
	o.Magnet = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) SetHash(v string) {
	o.Hash = &v
}

// GetInstant returns the Instant field value if set, zero value otherwise.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetInstant() bool {
	if o == nil || IsNil(o.Instant) {
		var ret bool
		return ret
	}
	return *o.Instant
}

// GetInstantOk returns a tuple with the Instant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetInstantOk() (*bool, bool) {
	if o == nil || IsNil(o.Instant) {
		return nil, false
	}
	return o.Instant, true
}

// HasInstant returns a boolean if a field has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) HasInstant() bool {
	if o != nil && !IsNil(o.Instant) {
		return true
	}

	return false
}

// SetInstant gets a reference to the given bool and assigns it to the Instant field.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) SetInstant(v bool) {
	o.Instant = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetError() MagnetUploadGet200ResponseDataMagnetsInnerError {
	if o == nil || IsNil(o.Error) {
		var ret MagnetUploadGet200ResponseDataMagnetsInnerError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) GetErrorOk() (*MagnetUploadGet200ResponseDataMagnetsInnerError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given MagnetUploadGet200ResponseDataMagnetsInnerError and assigns it to the Error field.
func (o *MagnetInstantGet200ResponseDataMagnetsInner) SetError(v MagnetUploadGet200ResponseDataMagnetsInnerError) {
	o.Error = &v
}

func (o MagnetInstantGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetInstantGet200ResponseDataMagnetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnet) {
		toSerialize["magnet"] = o.Magnet
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.Instant) {
		toSerialize["instant"] = o.Instant
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableMagnetInstantGet200ResponseDataMagnetsInner struct {
	value *MagnetInstantGet200ResponseDataMagnetsInner
	isSet bool
}

func (v NullableMagnetInstantGet200ResponseDataMagnetsInner) Get() *MagnetInstantGet200ResponseDataMagnetsInner {
	return v.value
}

func (v *NullableMagnetInstantGet200ResponseDataMagnetsInner) Set(val *MagnetInstantGet200ResponseDataMagnetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetInstantGet200ResponseDataMagnetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetInstantGet200ResponseDataMagnetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetInstantGet200ResponseDataMagnetsInner(val *MagnetInstantGet200ResponseDataMagnetsInner) *NullableMagnetInstantGet200ResponseDataMagnetsInner {
	return &NullableMagnetInstantGet200ResponseDataMagnetsInner{value: val, isSet: true}
}

func (v NullableMagnetInstantGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetInstantGet200ResponseDataMagnetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


