/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetStatusGet200ResponseDataMagnetsInnerLinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetStatusGet200ResponseDataMagnetsInnerLinksInner{}

// MagnetStatusGet200ResponseDataMagnetsInnerLinksInner struct for MagnetStatusGet200ResponseDataMagnetsInnerLinksInner
type MagnetStatusGet200ResponseDataMagnetsInnerLinksInner struct {
	Link *string `json:"link,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Size *int64 `json:"size,omitempty"`
}

// NewMagnetStatusGet200ResponseDataMagnetsInnerLinksInner instantiates a new MagnetStatusGet200ResponseDataMagnetsInnerLinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetStatusGet200ResponseDataMagnetsInnerLinksInner() *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner {
	this := MagnetStatusGet200ResponseDataMagnetsInnerLinksInner{}
	return &this
}

// NewMagnetStatusGet200ResponseDataMagnetsInnerLinksInnerWithDefaults instantiates a new MagnetStatusGet200ResponseDataMagnetsInnerLinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetStatusGet200ResponseDataMagnetsInnerLinksInnerWithDefaults() *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner {
	this := MagnetStatusGet200ResponseDataMagnetsInnerLinksInner{}
	return &this
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) SetLink(v string) {
	o.Link = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) SetFilename(v string) {
	o.Filename = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) SetSize(v int64) {
	o.Size = &v
}

func (o MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner struct {
	value *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner
	isSet bool
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) Get() *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner {
	return v.value
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) Set(val *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner(val *MagnetStatusGet200ResponseDataMagnetsInnerLinksInner) *NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner {
	return &NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner{value: val, isSet: true}
}

func (v NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetStatusGet200ResponseDataMagnetsInnerLinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


