/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the LinkRedirectorGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkRedirectorGet200ResponseData{}

// LinkRedirectorGet200ResponseData struct for LinkRedirectorGet200ResponseData
type LinkRedirectorGet200ResponseData struct {
	// Link(s) extracted.
	Links []string `json:"links,omitempty"`
}

// NewLinkRedirectorGet200ResponseData instantiates a new LinkRedirectorGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkRedirectorGet200ResponseData() *LinkRedirectorGet200ResponseData {
	this := LinkRedirectorGet200ResponseData{}
	return &this
}

// NewLinkRedirectorGet200ResponseDataWithDefaults instantiates a new LinkRedirectorGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkRedirectorGet200ResponseDataWithDefaults() *LinkRedirectorGet200ResponseData {
	this := LinkRedirectorGet200ResponseData{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *LinkRedirectorGet200ResponseData) GetLinks() []string {
	if o == nil || IsNil(o.Links) {
		var ret []string
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkRedirectorGet200ResponseData) GetLinksOk() ([]string, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *LinkRedirectorGet200ResponseData) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []string and assigns it to the Links field.
func (o *LinkRedirectorGet200ResponseData) SetLinks(v []string) {
	o.Links = v
}

func (o LinkRedirectorGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkRedirectorGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableLinkRedirectorGet200ResponseData struct {
	value *LinkRedirectorGet200ResponseData
	isSet bool
}

func (v NullableLinkRedirectorGet200ResponseData) Get() *LinkRedirectorGet200ResponseData {
	return v.value
}

func (v *NullableLinkRedirectorGet200ResponseData) Set(val *LinkRedirectorGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkRedirectorGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkRedirectorGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkRedirectorGet200ResponseData(val *LinkRedirectorGet200ResponseData) *NullableLinkRedirectorGet200ResponseData {
	return &NullableLinkRedirectorGet200ResponseData{value: val, isSet: true}
}

func (v NullableLinkRedirectorGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkRedirectorGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


