/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetUploadGet200ResponseDataMagnetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetUploadGet200ResponseDataMagnetsInner{}

// MagnetUploadGet200ResponseDataMagnetsInner struct for MagnetUploadGet200ResponseDataMagnetsInner
type MagnetUploadGet200ResponseDataMagnetsInner struct {
	Magnet *string `json:"magnet,omitempty"`
	Hash *string `json:"hash,omitempty"`
	Name *string `json:"name,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Ready *bool `json:"ready,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Error *MagnetUploadGet200ResponseDataMagnetsInnerError `json:"error,omitempty"`
}

// NewMagnetUploadGet200ResponseDataMagnetsInner instantiates a new MagnetUploadGet200ResponseDataMagnetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetUploadGet200ResponseDataMagnetsInner() *MagnetUploadGet200ResponseDataMagnetsInner {
	this := MagnetUploadGet200ResponseDataMagnetsInner{}
	return &this
}

// NewMagnetUploadGet200ResponseDataMagnetsInnerWithDefaults instantiates a new MagnetUploadGet200ResponseDataMagnetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetUploadGet200ResponseDataMagnetsInnerWithDefaults() *MagnetUploadGet200ResponseDataMagnetsInner {
	this := MagnetUploadGet200ResponseDataMagnetsInner{}
	return &this
}

// GetMagnet returns the Magnet field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetMagnet() string {
	if o == nil || IsNil(o.Magnet) {
		var ret string
		return ret
	}
	return *o.Magnet
}

// GetMagnetOk returns a tuple with the Magnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetMagnetOk() (*string, bool) {
	if o == nil || IsNil(o.Magnet) {
		return nil, false
	}
	return o.Magnet, true
}

// HasMagnet returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasMagnet() bool {
	if o != nil && !IsNil(o.Magnet) {
		return true
	}

	return false
}

// SetMagnet gets a reference to the given string and assigns it to the Magnet field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetMagnet(v string) {
	o.Magnet = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetHash(v string) {
	o.Hash = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetSize(v int64) {
	o.Size = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetReady(v bool) {
	o.Ready = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetId(v int64) {
	o.Id = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetError() MagnetUploadGet200ResponseDataMagnetsInnerError {
	if o == nil || IsNil(o.Error) {
		var ret MagnetUploadGet200ResponseDataMagnetsInnerError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) GetErrorOk() (*MagnetUploadGet200ResponseDataMagnetsInnerError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given MagnetUploadGet200ResponseDataMagnetsInnerError and assigns it to the Error field.
func (o *MagnetUploadGet200ResponseDataMagnetsInner) SetError(v MagnetUploadGet200ResponseDataMagnetsInnerError) {
	o.Error = &v
}

func (o MagnetUploadGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetUploadGet200ResponseDataMagnetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnet) {
		toSerialize["magnet"] = o.Magnet
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableMagnetUploadGet200ResponseDataMagnetsInner struct {
	value *MagnetUploadGet200ResponseDataMagnetsInner
	isSet bool
}

func (v NullableMagnetUploadGet200ResponseDataMagnetsInner) Get() *MagnetUploadGet200ResponseDataMagnetsInner {
	return v.value
}

func (v *NullableMagnetUploadGet200ResponseDataMagnetsInner) Set(val *MagnetUploadGet200ResponseDataMagnetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetUploadGet200ResponseDataMagnetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetUploadGet200ResponseDataMagnetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetUploadGet200ResponseDataMagnetsInner(val *MagnetUploadGet200ResponseDataMagnetsInner) *NullableMagnetUploadGet200ResponseDataMagnetsInner {
	return &NullableMagnetUploadGet200ResponseDataMagnetsInner{value: val, isSet: true}
}

func (v NullableMagnetUploadGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetUploadGet200ResponseDataMagnetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


