/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the HostsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostsGet200ResponseData{}

// HostsGet200ResponseData struct for HostsGet200ResponseData
type HostsGet200ResponseData struct {
	Hosts *map[string]HostsGet200ResponseDataHostsValue `json:"hosts,omitempty"`
	Streams *map[string]HostsGet200ResponseDataStreamsValue `json:"streams,omitempty"`
	Redirectors *map[string]HostsGet200ResponseDataRedirectorsValue `json:"redirectors,omitempty"`
}

// NewHostsGet200ResponseData instantiates a new HostsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostsGet200ResponseData() *HostsGet200ResponseData {
	this := HostsGet200ResponseData{}
	return &this
}

// NewHostsGet200ResponseDataWithDefaults instantiates a new HostsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostsGet200ResponseDataWithDefaults() *HostsGet200ResponseData {
	this := HostsGet200ResponseData{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *HostsGet200ResponseData) GetHosts() map[string]HostsGet200ResponseDataHostsValue {
	if o == nil || IsNil(o.Hosts) {
		var ret map[string]HostsGet200ResponseDataHostsValue
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsGet200ResponseData) GetHostsOk() (*map[string]HostsGet200ResponseDataHostsValue, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *HostsGet200ResponseData) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given map[string]HostsGet200ResponseDataHostsValue and assigns it to the Hosts field.
func (o *HostsGet200ResponseData) SetHosts(v map[string]HostsGet200ResponseDataHostsValue) {
	o.Hosts = &v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *HostsGet200ResponseData) GetStreams() map[string]HostsGet200ResponseDataStreamsValue {
	if o == nil || IsNil(o.Streams) {
		var ret map[string]HostsGet200ResponseDataStreamsValue
		return ret
	}
	return *o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsGet200ResponseData) GetStreamsOk() (*map[string]HostsGet200ResponseDataStreamsValue, bool) {
	if o == nil || IsNil(o.Streams) {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *HostsGet200ResponseData) HasStreams() bool {
	if o != nil && !IsNil(o.Streams) {
		return true
	}

	return false
}

// SetStreams gets a reference to the given map[string]HostsGet200ResponseDataStreamsValue and assigns it to the Streams field.
func (o *HostsGet200ResponseData) SetStreams(v map[string]HostsGet200ResponseDataStreamsValue) {
	o.Streams = &v
}

// GetRedirectors returns the Redirectors field value if set, zero value otherwise.
func (o *HostsGet200ResponseData) GetRedirectors() map[string]HostsGet200ResponseDataRedirectorsValue {
	if o == nil || IsNil(o.Redirectors) {
		var ret map[string]HostsGet200ResponseDataRedirectorsValue
		return ret
	}
	return *o.Redirectors
}

// GetRedirectorsOk returns a tuple with the Redirectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsGet200ResponseData) GetRedirectorsOk() (*map[string]HostsGet200ResponseDataRedirectorsValue, bool) {
	if o == nil || IsNil(o.Redirectors) {
		return nil, false
	}
	return o.Redirectors, true
}

// HasRedirectors returns a boolean if a field has been set.
func (o *HostsGet200ResponseData) HasRedirectors() bool {
	if o != nil && !IsNil(o.Redirectors) {
		return true
	}

	return false
}

// SetRedirectors gets a reference to the given map[string]HostsGet200ResponseDataRedirectorsValue and assigns it to the Redirectors field.
func (o *HostsGet200ResponseData) SetRedirectors(v map[string]HostsGet200ResponseDataRedirectorsValue) {
	o.Redirectors = &v
}

func (o HostsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.Streams) {
		toSerialize["streams"] = o.Streams
	}
	if !IsNil(o.Redirectors) {
		toSerialize["redirectors"] = o.Redirectors
	}
	return toSerialize, nil
}

type NullableHostsGet200ResponseData struct {
	value *HostsGet200ResponseData
	isSet bool
}

func (v NullableHostsGet200ResponseData) Get() *HostsGet200ResponseData {
	return v.value
}

func (v *NullableHostsGet200ResponseData) Set(val *HostsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableHostsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableHostsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostsGet200ResponseData(val *HostsGet200ResponseData) *NullableHostsGet200ResponseData {
	return &NullableHostsGet200ResponseData{value: val, isSet: true}
}

func (v NullableHostsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


