/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetUploadFilePost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetUploadFilePost200ResponseData{}

// MagnetUploadFilePost200ResponseData struct for MagnetUploadFilePost200ResponseData
type MagnetUploadFilePost200ResponseData struct {
	Files []MagnetUploadFilePost200ResponseDataFilesInner `json:"files,omitempty"`
}

// NewMagnetUploadFilePost200ResponseData instantiates a new MagnetUploadFilePost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetUploadFilePost200ResponseData() *MagnetUploadFilePost200ResponseData {
	this := MagnetUploadFilePost200ResponseData{}
	return &this
}

// NewMagnetUploadFilePost200ResponseDataWithDefaults instantiates a new MagnetUploadFilePost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetUploadFilePost200ResponseDataWithDefaults() *MagnetUploadFilePost200ResponseData {
	this := MagnetUploadFilePost200ResponseData{}
	return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *MagnetUploadFilePost200ResponseData) GetFiles() []MagnetUploadFilePost200ResponseDataFilesInner {
	if o == nil || IsNil(o.Files) {
		var ret []MagnetUploadFilePost200ResponseDataFilesInner
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetUploadFilePost200ResponseData) GetFilesOk() ([]MagnetUploadFilePost200ResponseDataFilesInner, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *MagnetUploadFilePost200ResponseData) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []MagnetUploadFilePost200ResponseDataFilesInner and assigns it to the Files field.
func (o *MagnetUploadFilePost200ResponseData) SetFiles(v []MagnetUploadFilePost200ResponseDataFilesInner) {
	o.Files = v
}

func (o MagnetUploadFilePost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetUploadFilePost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableMagnetUploadFilePost200ResponseData struct {
	value *MagnetUploadFilePost200ResponseData
	isSet bool
}

func (v NullableMagnetUploadFilePost200ResponseData) Get() *MagnetUploadFilePost200ResponseData {
	return v.value
}

func (v *NullableMagnetUploadFilePost200ResponseData) Set(val *MagnetUploadFilePost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetUploadFilePost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetUploadFilePost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetUploadFilePost200ResponseData(val *MagnetUploadFilePost200ResponseData) *NullableMagnetUploadFilePost200ResponseData {
	return &NullableMagnetUploadFilePost200ResponseData{value: val, isSet: true}
}

func (v NullableMagnetUploadFilePost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetUploadFilePost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


