/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the HostsDomainsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostsDomainsGet200ResponseData{}

// HostsDomainsGet200ResponseData struct for HostsDomainsGet200ResponseData
type HostsDomainsGet200ResponseData struct {
	Hosts []string `json:"hosts,omitempty"`
	Streams []string `json:"streams,omitempty"`
	Redirectors []string `json:"redirectors,omitempty"`
}

// NewHostsDomainsGet200ResponseData instantiates a new HostsDomainsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostsDomainsGet200ResponseData() *HostsDomainsGet200ResponseData {
	this := HostsDomainsGet200ResponseData{}
	return &this
}

// NewHostsDomainsGet200ResponseDataWithDefaults instantiates a new HostsDomainsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostsDomainsGet200ResponseDataWithDefaults() *HostsDomainsGet200ResponseData {
	this := HostsDomainsGet200ResponseData{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *HostsDomainsGet200ResponseData) GetHosts() []string {
	if o == nil || IsNil(o.Hosts) {
		var ret []string
		return ret
	}
	return o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsDomainsGet200ResponseData) GetHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *HostsDomainsGet200ResponseData) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *HostsDomainsGet200ResponseData) SetHosts(v []string) {
	o.Hosts = v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *HostsDomainsGet200ResponseData) GetStreams() []string {
	if o == nil || IsNil(o.Streams) {
		var ret []string
		return ret
	}
	return o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsDomainsGet200ResponseData) GetStreamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Streams) {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *HostsDomainsGet200ResponseData) HasStreams() bool {
	if o != nil && !IsNil(o.Streams) {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []string and assigns it to the Streams field.
func (o *HostsDomainsGet200ResponseData) SetStreams(v []string) {
	o.Streams = v
}

// GetRedirectors returns the Redirectors field value if set, zero value otherwise.
func (o *HostsDomainsGet200ResponseData) GetRedirectors() []string {
	if o == nil || IsNil(o.Redirectors) {
		var ret []string
		return ret
	}
	return o.Redirectors
}

// GetRedirectorsOk returns a tuple with the Redirectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostsDomainsGet200ResponseData) GetRedirectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Redirectors) {
		return nil, false
	}
	return o.Redirectors, true
}

// HasRedirectors returns a boolean if a field has been set.
func (o *HostsDomainsGet200ResponseData) HasRedirectors() bool {
	if o != nil && !IsNil(o.Redirectors) {
		return true
	}

	return false
}

// SetRedirectors gets a reference to the given []string and assigns it to the Redirectors field.
func (o *HostsDomainsGet200ResponseData) SetRedirectors(v []string) {
	o.Redirectors = v
}

func (o HostsDomainsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostsDomainsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.Streams) {
		toSerialize["streams"] = o.Streams
	}
	if !IsNil(o.Redirectors) {
		toSerialize["redirectors"] = o.Redirectors
	}
	return toSerialize, nil
}

type NullableHostsDomainsGet200ResponseData struct {
	value *HostsDomainsGet200ResponseData
	isSet bool
}

func (v NullableHostsDomainsGet200ResponseData) Get() *HostsDomainsGet200ResponseData {
	return v.value
}

func (v *NullableHostsDomainsGet200ResponseData) Set(val *HostsDomainsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableHostsDomainsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableHostsDomainsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostsDomainsGet200ResponseData(val *HostsDomainsGet200ResponseData) *NullableHostsDomainsGet200ResponseData {
	return &NullableHostsDomainsGet200ResponseData{value: val, isSet: true}
}

func (v NullableHostsDomainsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostsDomainsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


