/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetRestartGet200ResponseDataMagnetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetRestartGet200ResponseDataMagnetsInner{}

// MagnetRestartGet200ResponseDataMagnetsInner struct for MagnetRestartGet200ResponseDataMagnetsInner
type MagnetRestartGet200ResponseDataMagnetsInner struct {
	Magnet *string `json:"magnet,omitempty"`
	Message *string `json:"message,omitempty"`
	Error *MagnetRestartGet200ResponseDataMagnetsInnerError `json:"error,omitempty"`
}

// NewMagnetRestartGet200ResponseDataMagnetsInner instantiates a new MagnetRestartGet200ResponseDataMagnetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetRestartGet200ResponseDataMagnetsInner() *MagnetRestartGet200ResponseDataMagnetsInner {
	this := MagnetRestartGet200ResponseDataMagnetsInner{}
	return &this
}

// NewMagnetRestartGet200ResponseDataMagnetsInnerWithDefaults instantiates a new MagnetRestartGet200ResponseDataMagnetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetRestartGet200ResponseDataMagnetsInnerWithDefaults() *MagnetRestartGet200ResponseDataMagnetsInner {
	this := MagnetRestartGet200ResponseDataMagnetsInner{}
	return &this
}

// GetMagnet returns the Magnet field value if set, zero value otherwise.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetMagnet() string {
	if o == nil || IsNil(o.Magnet) {
		var ret string
		return ret
	}
	return *o.Magnet
}

// GetMagnetOk returns a tuple with the Magnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetMagnetOk() (*string, bool) {
	if o == nil || IsNil(o.Magnet) {
		return nil, false
	}
	return o.Magnet, true
}

// HasMagnet returns a boolean if a field has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) HasMagnet() bool {
	if o != nil && !IsNil(o.Magnet) {
		return true
	}

	return false
}

// SetMagnet gets a reference to the given string and assigns it to the Magnet field.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) SetMagnet(v string) {
	o.Magnet = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) SetMessage(v string) {
	o.Message = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetError() MagnetRestartGet200ResponseDataMagnetsInnerError {
	if o == nil || IsNil(o.Error) {
		var ret MagnetRestartGet200ResponseDataMagnetsInnerError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) GetErrorOk() (*MagnetRestartGet200ResponseDataMagnetsInnerError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given MagnetRestartGet200ResponseDataMagnetsInnerError and assigns it to the Error field.
func (o *MagnetRestartGet200ResponseDataMagnetsInner) SetError(v MagnetRestartGet200ResponseDataMagnetsInnerError) {
	o.Error = &v
}

func (o MagnetRestartGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetRestartGet200ResponseDataMagnetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnet) {
		toSerialize["magnet"] = o.Magnet
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableMagnetRestartGet200ResponseDataMagnetsInner struct {
	value *MagnetRestartGet200ResponseDataMagnetsInner
	isSet bool
}

func (v NullableMagnetRestartGet200ResponseDataMagnetsInner) Get() *MagnetRestartGet200ResponseDataMagnetsInner {
	return v.value
}

func (v *NullableMagnetRestartGet200ResponseDataMagnetsInner) Set(val *MagnetRestartGet200ResponseDataMagnetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetRestartGet200ResponseDataMagnetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetRestartGet200ResponseDataMagnetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetRestartGet200ResponseDataMagnetsInner(val *MagnetRestartGet200ResponseDataMagnetsInner) *NullableMagnetRestartGet200ResponseDataMagnetsInner {
	return &NullableMagnetRestartGet200ResponseDataMagnetsInner{value: val, isSet: true}
}

func (v NullableMagnetRestartGet200ResponseDataMagnetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetRestartGet200ResponseDataMagnetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


