/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetInstantGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetInstantGet200ResponseData{}

// MagnetInstantGet200ResponseData struct for MagnetInstantGet200ResponseData
type MagnetInstantGet200ResponseData struct {
	Magnets []MagnetInstantGet200ResponseDataMagnetsInner `json:"magnets,omitempty"`
}

// NewMagnetInstantGet200ResponseData instantiates a new MagnetInstantGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetInstantGet200ResponseData() *MagnetInstantGet200ResponseData {
	this := MagnetInstantGet200ResponseData{}
	return &this
}

// NewMagnetInstantGet200ResponseDataWithDefaults instantiates a new MagnetInstantGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetInstantGet200ResponseDataWithDefaults() *MagnetInstantGet200ResponseData {
	this := MagnetInstantGet200ResponseData{}
	return &this
}

// GetMagnets returns the Magnets field value if set, zero value otherwise.
func (o *MagnetInstantGet200ResponseData) GetMagnets() []MagnetInstantGet200ResponseDataMagnetsInner {
	if o == nil || IsNil(o.Magnets) {
		var ret []MagnetInstantGet200ResponseDataMagnetsInner
		return ret
	}
	return o.Magnets
}

// GetMagnetsOk returns a tuple with the Magnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetInstantGet200ResponseData) GetMagnetsOk() ([]MagnetInstantGet200ResponseDataMagnetsInner, bool) {
	if o == nil || IsNil(o.Magnets) {
		return nil, false
	}
	return o.Magnets, true
}

// HasMagnets returns a boolean if a field has been set.
func (o *MagnetInstantGet200ResponseData) HasMagnets() bool {
	if o != nil && !IsNil(o.Magnets) {
		return true
	}

	return false
}

// SetMagnets gets a reference to the given []MagnetInstantGet200ResponseDataMagnetsInner and assigns it to the Magnets field.
func (o *MagnetInstantGet200ResponseData) SetMagnets(v []MagnetInstantGet200ResponseDataMagnetsInner) {
	o.Magnets = v
}

func (o MagnetInstantGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetInstantGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnets) {
		toSerialize["magnets"] = o.Magnets
	}
	return toSerialize, nil
}

type NullableMagnetInstantGet200ResponseData struct {
	value *MagnetInstantGet200ResponseData
	isSet bool
}

func (v NullableMagnetInstantGet200ResponseData) Get() *MagnetInstantGet200ResponseData {
	return v.value
}

func (v *NullableMagnetInstantGet200ResponseData) Set(val *MagnetInstantGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetInstantGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetInstantGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetInstantGet200ResponseData(val *MagnetInstantGet200ResponseData) *NullableMagnetInstantGet200ResponseData {
	return &NullableMagnetInstantGet200ResponseData{value: val, isSet: true}
}

func (v NullableMagnetInstantGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetInstantGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


