/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MagnetRestartGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagnetRestartGet200ResponseData{}

// MagnetRestartGet200ResponseData struct for MagnetRestartGet200ResponseData
type MagnetRestartGet200ResponseData struct {
	Magnets []MagnetRestartGet200ResponseDataMagnetsInner `json:"magnets,omitempty"`
}

// NewMagnetRestartGet200ResponseData instantiates a new MagnetRestartGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagnetRestartGet200ResponseData() *MagnetRestartGet200ResponseData {
	this := MagnetRestartGet200ResponseData{}
	return &this
}

// NewMagnetRestartGet200ResponseDataWithDefaults instantiates a new MagnetRestartGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagnetRestartGet200ResponseDataWithDefaults() *MagnetRestartGet200ResponseData {
	this := MagnetRestartGet200ResponseData{}
	return &this
}

// GetMagnets returns the Magnets field value if set, zero value otherwise.
func (o *MagnetRestartGet200ResponseData) GetMagnets() []MagnetRestartGet200ResponseDataMagnetsInner {
	if o == nil || IsNil(o.Magnets) {
		var ret []MagnetRestartGet200ResponseDataMagnetsInner
		return ret
	}
	return o.Magnets
}

// GetMagnetsOk returns a tuple with the Magnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagnetRestartGet200ResponseData) GetMagnetsOk() ([]MagnetRestartGet200ResponseDataMagnetsInner, bool) {
	if o == nil || IsNil(o.Magnets) {
		return nil, false
	}
	return o.Magnets, true
}

// HasMagnets returns a boolean if a field has been set.
func (o *MagnetRestartGet200ResponseData) HasMagnets() bool {
	if o != nil && !IsNil(o.Magnets) {
		return true
	}

	return false
}

// SetMagnets gets a reference to the given []MagnetRestartGet200ResponseDataMagnetsInner and assigns it to the Magnets field.
func (o *MagnetRestartGet200ResponseData) SetMagnets(v []MagnetRestartGet200ResponseDataMagnetsInner) {
	o.Magnets = v
}

func (o MagnetRestartGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagnetRestartGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnets) {
		toSerialize["magnets"] = o.Magnets
	}
	return toSerialize, nil
}

type NullableMagnetRestartGet200ResponseData struct {
	value *MagnetRestartGet200ResponseData
	isSet bool
}

func (v NullableMagnetRestartGet200ResponseData) Get() *MagnetRestartGet200ResponseData {
	return v.value
}

func (v *NullableMagnetRestartGet200ResponseData) Set(val *MagnetRestartGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMagnetRestartGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMagnetRestartGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagnetRestartGet200ResponseData(val *MagnetRestartGet200ResponseData) *NullableMagnetRestartGet200ResponseData {
	return &NullableMagnetRestartGet200ResponseData{value: val, isSet: true}
}

func (v NullableMagnetRestartGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagnetRestartGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


