/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the LinkStreamingGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkStreamingGet200ResponseData{}

// LinkStreamingGet200ResponseData struct for LinkStreamingGet200ResponseData
type LinkStreamingGet200ResponseData struct {
	Filename *string `json:"filename,omitempty"`
	Filesize *int64 `json:"filesize,omitempty"`
	Host *string `json:"host,omitempty"`
	HostDomain *string `json:"hostDomain,omitempty"`
	Id *string `json:"id,omitempty"`
	Link *string `json:"link,omitempty"`
	Paws *bool `json:"paws,omitempty"`
	Streams []LinkStreamingGet200ResponseDataStreamsInner `json:"streams,omitempty"`
}

// NewLinkStreamingGet200ResponseData instantiates a new LinkStreamingGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkStreamingGet200ResponseData() *LinkStreamingGet200ResponseData {
	this := LinkStreamingGet200ResponseData{}
	return &this
}

// NewLinkStreamingGet200ResponseDataWithDefaults instantiates a new LinkStreamingGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkStreamingGet200ResponseDataWithDefaults() *LinkStreamingGet200ResponseData {
	this := LinkStreamingGet200ResponseData{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *LinkStreamingGet200ResponseData) SetFilename(v string) {
	o.Filename = &v
}

// GetFilesize returns the Filesize field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetFilesize() int64 {
	if o == nil || IsNil(o.Filesize) {
		var ret int64
		return ret
	}
	return *o.Filesize
}

// GetFilesizeOk returns a tuple with the Filesize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetFilesizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Filesize) {
		return nil, false
	}
	return o.Filesize, true
}

// HasFilesize returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasFilesize() bool {
	if o != nil && !IsNil(o.Filesize) {
		return true
	}

	return false
}

// SetFilesize gets a reference to the given int64 and assigns it to the Filesize field.
func (o *LinkStreamingGet200ResponseData) SetFilesize(v int64) {
	o.Filesize = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *LinkStreamingGet200ResponseData) SetHost(v string) {
	o.Host = &v
}

// GetHostDomain returns the HostDomain field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetHostDomain() string {
	if o == nil || IsNil(o.HostDomain) {
		var ret string
		return ret
	}
	return *o.HostDomain
}

// GetHostDomainOk returns a tuple with the HostDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetHostDomainOk() (*string, bool) {
	if o == nil || IsNil(o.HostDomain) {
		return nil, false
	}
	return o.HostDomain, true
}

// HasHostDomain returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasHostDomain() bool {
	if o != nil && !IsNil(o.HostDomain) {
		return true
	}

	return false
}

// SetHostDomain gets a reference to the given string and assigns it to the HostDomain field.
func (o *LinkStreamingGet200ResponseData) SetHostDomain(v string) {
	o.HostDomain = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LinkStreamingGet200ResponseData) SetId(v string) {
	o.Id = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *LinkStreamingGet200ResponseData) SetLink(v string) {
	o.Link = &v
}

// GetPaws returns the Paws field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetPaws() bool {
	if o == nil || IsNil(o.Paws) {
		var ret bool
		return ret
	}
	return *o.Paws
}

// GetPawsOk returns a tuple with the Paws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetPawsOk() (*bool, bool) {
	if o == nil || IsNil(o.Paws) {
		return nil, false
	}
	return o.Paws, true
}

// HasPaws returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasPaws() bool {
	if o != nil && !IsNil(o.Paws) {
		return true
	}

	return false
}

// SetPaws gets a reference to the given bool and assigns it to the Paws field.
func (o *LinkStreamingGet200ResponseData) SetPaws(v bool) {
	o.Paws = &v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *LinkStreamingGet200ResponseData) GetStreams() []LinkStreamingGet200ResponseDataStreamsInner {
	if o == nil || IsNil(o.Streams) {
		var ret []LinkStreamingGet200ResponseDataStreamsInner
		return ret
	}
	return o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStreamingGet200ResponseData) GetStreamsOk() ([]LinkStreamingGet200ResponseDataStreamsInner, bool) {
	if o == nil || IsNil(o.Streams) {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *LinkStreamingGet200ResponseData) HasStreams() bool {
	if o != nil && !IsNil(o.Streams) {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []LinkStreamingGet200ResponseDataStreamsInner and assigns it to the Streams field.
func (o *LinkStreamingGet200ResponseData) SetStreams(v []LinkStreamingGet200ResponseDataStreamsInner) {
	o.Streams = v
}

func (o LinkStreamingGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkStreamingGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Filesize) {
		toSerialize["filesize"] = o.Filesize
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.HostDomain) {
		toSerialize["hostDomain"] = o.HostDomain
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.Paws) {
		toSerialize["paws"] = o.Paws
	}
	if !IsNil(o.Streams) {
		toSerialize["streams"] = o.Streams
	}
	return toSerialize, nil
}

type NullableLinkStreamingGet200ResponseData struct {
	value *LinkStreamingGet200ResponseData
	isSet bool
}

func (v NullableLinkStreamingGet200ResponseData) Get() *LinkStreamingGet200ResponseData {
	return v.value
}

func (v *NullableLinkStreamingGet200ResponseData) Set(val *LinkStreamingGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkStreamingGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkStreamingGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkStreamingGet200ResponseData(val *LinkStreamingGet200ResponseData) *NullableLinkStreamingGet200ResponseData {
	return &NullableLinkStreamingGet200ResponseData{value: val, isSet: true}
}

func (v NullableLinkStreamingGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkStreamingGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


